<?php

use Illuminate\Database\Seeder;

class ProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('profiles')->delete();
        
        \DB::table('profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'first_name' => 'Admin',
                'last_name' => 'Istrator',
                'telephone' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address1' => NULL,
                'address2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2017-12-28 15:27:35',
                'updated_at' => '2019-01-18 10:58:00',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 2,
                'first_name' => 'Stephane',
                'last_name' => 'Leroux',
                'telephone' => '613-370-0275',
                'image' => '1548022561.png',
                'civic_number' => '1216',
                'address1' => 'Ste Marie Rd',
                'address2' => NULL,
                'city' => 'Embrun',
                'province' => 'Ontario',
                'postal_code' => 'K0A 1W0',
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2017-12-28 15:28:06',
                'updated_at' => '2019-02-09 07:19:52',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 3,
                'first_name' => 'Stacie',
                'last_name' => 'Haynes',
                'telephone' => '613-327-4722',
                'image' => NULL,
                'civic_number' => NULL,
                'address1' => NULL,
                'address2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2017-12-28 15:28:26',
                'updated_at' => '2017-12-28 15:28:26',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 4,
                'first_name' => 'Hugues',
                'last_name' => 'Leroux',
                'telephone' => '613-255-7754',
                'image' => NULL,
                'civic_number' => NULL,
                'address1' => NULL,
                'address2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2017-12-28 15:28:26',
                'updated_at' => '2017-12-28 15:28:26',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 5,
                'first_name' => 'Luc',
                'last_name' => 'Leveille',
                'telephone' => '613-204-7525',
                'image' => NULL,
                'civic_number' => NULL,
                'address1' => NULL,
                'address2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2017-12-28 15:28:26',
                'updated_at' => '2017-12-28 15:28:26',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 6,
                'first_name' => 'Julien',
                'last_name' => 'Tremblay',
                'telephone' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address1' => NULL,
                'address2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2018-06-05 18:40:29',
                'updated_at' => '2018-06-08 12:47:23',                
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 7,
                'first_name' => 'Brenda',
                'last_name' => 'Haynes',
                'telephone' => '613-987-2995',
                'image' => NULL,
                'civic_number' => NULL,
                'address1' => NULL,
                'address2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'deleted_at' => NULL,
                'created_at' => '2018-06-05 18:40:15',
                'updated_at' => '2018-06-05 18:40:15',
            ),
        ));
        
        
    }
}