<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'administrator',
                'email' => 'admin@thewoodbarn.ca',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => 'Admin',
                'last_name' => 'Istrator',
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'The Admin Specialists',
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 0,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => '2019-02-12 11:58:45',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 11:58:45',
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'lerouxs',
                'email' => 'stleroux@hotmail.ca',
                'public_email' => 1,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => 'Stephane',
                'last_name' => 'Leroux',
                'telephone' => '613-370-0275',
                'cell' => '613-402-0275',
                'fax' => '613-123-4567',
                'website' => 'thewoodbarn.ca',
                'company_name' => 'TheWoodBarn.ca',
                'image' => '1565629121.jpg',
                'civic_number' => '1216',
                'address_1' => 'Ste Marie Rd',
                'address_2' => NULL,
                'city' => 'Embrun',
                'province' => 'On',
                'postal_code' => 'K0A 1W0',
                'notes' => 'Nothing special',
                'dart_doubleOut' => 7,
                'invoicer_client' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => NULL,
                'landing_page_id' => NULL,
                'rows_per_page' => NULL,
                'display_size' => 'normal',
                'action_buttons' => NULL,
                'author_format' => NULL,
                'alert_fade_time' => NULL,
                'layout' => 1,
                'remember_token' => 'WxMi63i8kJfsgZIWuBrci7LFq3nrHFyIcms9DEobCQpbXmCQAQOv3ZUsovkU',
                'previous_login_date' => '2019-12-21 20:00:03',
                'last_login_date' => '2019-12-23 11:40:26',
                'login_count' => 215,
                'email_verified_at' => NULL,
                'created_at' => '2016-06-21 08:52:05',
                'updated_at' => '2019-12-23 11:40:26',
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'hayness',
                'email' => 'stacie@hotmail.com',
                'public_email' => 0,
                'password' => '$2y$10$3MWYjM4NqbZ3Vf7y9HYbleivjht8ExnuoLD6tDl/qFZLU1.pi9sNG',
                'first_name' => 'Stacie',
                'last_name' => 'Haynes',
                'telephone' => '613-370-0275',
                'cell' => '613-327-4722',
                'fax' => NULL,
                'website' => 'dsfdsfds',
                'company_name' => 'ABC Company',
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 16,
                'invoicer_client' => 1,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => NULL,
                'landing_page_id' => NULL,
                'rows_per_page' => NULL,
                'display_size' => 'normal',
                'action_buttons' => NULL,
                'author_format' => NULL,
                'alert_fade_time' => NULL,
                'layout' => 1,
                'remember_token' => 'yha9dD1yOovX9MYchx2iXitqJ0avITkPNTY9cLQDTKLCds8FjmfhdlFv04Kr',
                'previous_login_date' => '2019-12-10 15:06:32',
                'last_login_date' => '2019-09-27 15:11:28',
                'login_count' => 45,
                'email_verified_at' => NULL,
                'created_at' => '2018-11-02 11:55:55',
                'updated_at' => '2019-12-10 15:10:39',
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'lerouxh',
                'email' => 'hugues.leroux@rogers.com',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => 'Hugues',
                'last_name' => 'Leroux',
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Wade Redden Corporation',
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 0,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => '2019-02-12 11:17:35',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 11:59:48',
                'updated_at' => '2019-11-21 16:49:01',
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'leveillel',
                'email' => 'luc.leveille@icloud.com',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => 'Luc',
                'last_name' => 'Leveille',
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 10,
                'invoicer_client' => 0,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => '2019-02-12 11:15:48',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 12:00:21',
                'updated_at' => '2019-11-21 16:49:14',
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'tremblayj',
                'email' => 'julien.tremblay@dfo-mpo.gc.ca',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => 'Julien',
                'last_name' => 'Tremblay',
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'dart_doubleOut' => 5,
                'invoicer_client' => 0,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'previous_login_date' => NULL,
                'last_login_date' => '2019-02-12 12:02:16',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 12:02:16',
                'updated_at' => '2019-11-21 16:49:25',
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'haynesb',
                'email' => 'brenda.haynes@hotmail.com',
                'public_email' => 0,
                'password' => '$2y$10$MDWeLaGsK37mO9M5TJh/wevnbilYZYwHSSvXSkdQQmSnAfK4UvM.2',
                'first_name' => 'Brenda',
                'last_name' => 'Haynes',
                'telephone' => '613-987-2995',
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'company_name' => 'Brenda Haynes',
                'image' => '1573907448.jpg',
                'civic_number' => '14679',
                'address_1' => 'Shane Rd',
                'address_2' => NULL,
                'city' => 'Chrysler',
                'province' => 'On',
                'postal_code' => 'K0A 1R0',
                'notes' => NULL,
                'dart_doubleOut' => 2,
                'invoicer_client' => 0,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 0,
                'landing_page_id' => '',
                'rows_per_page' => 0,
                'display_size' => 'normal',
                'action_buttons' => '',
                'author_format' => '',
                'alert_fade_time' => 0,
                'layout' => 1,
                'remember_token' => NULL,
                'previous_login_date' => '2019-10-27 06:24:37',
                'last_login_date' => '2019-02-12 12:02:46',
                'login_count' => 2,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 12:02:46',
                'updated_at' => '2019-12-06 08:08:00',
                'deleted_at' => NULL,
                'approved' => 1,
            ),
            
        ));
        
        
    }
}