<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'administrator',
                'email' => 'admin@thewoodbarn.ca',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => NULL,
                'last_name' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'last_login_date' => '2019-02-12 11:58:45',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 11:58:45',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'lerouxs',
                'email' => 'stleroux@hotmail.ca',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => 'Stephane',
                'last_name' => 'Leroux',
                'telephone' => '613-370-0275',
                'cell' => '613-402-0275',
                'fax' => '613-123-4567',
                'website' => 'thewoodbarn.ca',
                'image' => NULL,
                'civic_number' => '1216',
                'address_1' => 'Ste Marie Rd',
                'address_2' => NULL,
                'city' => 'Embrun',
                'province' => 'On',
                'postal_code' => 'K0A 1W0',
                'notes' => 'Nothing special',
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 0,
                'landing_page_id' => '',
                'rows_per_page' => 0,
                'display_size' => 'normal',
                'action_buttons' => '',
                'author_format' => '',
                'alert_fade_time' => 0,
                'layout' => 1,
                'remember_token' => 'LVoNJ1hNQUZ6MKD5MH2tQ5Chpg2ebxU15idxxM2pRP1YDaS9akGE73LNnmN1',
                'last_login_date' => '2019-08-01 22:04:43',
                'login_count' => 25,
                'email_verified_at' => NULL,
                'created_at' => '2018-10-24 16:31:15',
                'updated_at' => '2019-08-11 21:56:33',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'hayness',
                'email' => 'stacie@hotmail.com',
                'public_email' => 0,
                'password' => '$2y$10$968BD2.11mQxrGfKeBWRj.dcgWLalEGjWHX1XKmxk.H.ZP6YPLGau',
                'first_name' => NULL,
                'last_name' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => '55DOB2ljWdlxmhPsrdHq4RPmZLmlSJUgZqAotkJcpUIYEall3mD2hPJZoXHs',
                'last_login_date' => '0000-00-00 00:00:00',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2018-11-02 11:55:55',
                'updated_at' => '2018-11-02 11:55:55',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'lerouxh',
                'email' => 'hugues.leroux@rogers.com',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => NULL,
                'last_name' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'last_login_date' => '2019-02-12 11:17:35',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 11:59:48',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'leveillel',
                'email' => 'luc.leveille@icloud.com',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => NULL,
                'last_name' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'last_login_date' => '2019-02-12 11:15:48',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 12:00:21',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'tremblayj',
                'email' => 'julien.tremblay@dfo-mpo.gc.ca',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => NULL,
                'last_name' => NULL,
                'telephone' => NULL,
                'cell' => NULL,
                'fax' => NULL,
                'website' => NULL,
                'image' => NULL,
                'civic_number' => NULL,
                'address_1' => NULL,
                'address_2' => NULL,
                'city' => NULL,
                'province' => NULL,
                'postal_code' => NULL,
                'notes' => NULL,
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 1,
                'landing_page_id' => '41',
                'rows_per_page' => 15,
                'display_size' => 'normal',
                'action_buttons' => '1',
                'author_format' => '1',
                'alert_fade_time' => 5000,
                'layout' => 1,
                'remember_token' => NULL,
                'last_login_date' => '2019-02-12 12:02:16',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 12:02:16',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'haynesb',
                'email' => 'brenda.haynes@hotmail.com',
                'public_email' => 0,
                'password' => '$2y$10$a3VOdvKkx9i6yZ3soekk/uhxC8mX76Enn9KJeOCilynZhHQvzitFe',
                'first_name' => '1',
                'last_name' => '2',
                'telephone' => '4',
                'cell' => '5',
                'fax' => '6',
                'website' => '7',
                'image' => '1565574347.jpg',
                'civic_number' => '8',
                'address_1' => '9',
                'address_2' => '10',
                'city' => '11',
                'province' => '12',
                'postal_code' => '13',
                'notes' => '141516',
                'frontendStyle' => 'slate',
                'backendStyle' => 'bootstrap',
                'date_format' => 0,
                'landing_page_id' => '',
                'rows_per_page' => 0,
                'display_size' => 'normal',
                'action_buttons' => '',
                'author_format' => '',
                'alert_fade_time' => 0,
                'layout' => 1,
                'remember_token' => NULL,
                'last_login_date' => '2019-02-12 12:02:46',
                'login_count' => 0,
                'email_verified_at' => NULL,
                'created_at' => '2019-02-12 12:02:46',
                'updated_at' => '2019-08-11 21:46:50',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}